#!/bin/bash
while [ "$select" != "NO" -a "$select" != "YES" ]; do
    select=$(echo -e 'NO\nYES' | dmenu -nb '#2f343f' -nf '#676E7D' -sb '#2f343f' -sf '#f3f4f5' -i -p "Are you sure you want to logout?" -l 2)
    [ -z "$select" ] && exit 0
done
[ "$select" = "NO" ] && exit 0
i3-msg exit
