
theme = "simpledark"

[editor]
line-number = "relative"
cursorline = true
gutters = ["diagnostics", "line-numbers", "diff"]
auto-format = false
auto-pairs = false
completion-timeout = 5
completion-replace = false
preview-completion-insert = true
text-width = 80
color-modes = true
true-color = true
undercurl = true

[editor.statusline]
left = [
    "mode", "spinner", "version-control", "file-name", "read-only-indicator",
    "file-modification-indicator", "file-line-ending", "file-encoding", "file-type"
]
center = []
right = ["diagnostics", "selections", "register", "position"]

[editor.file-picker]
hidden = false
git-ignore = false

[editor.lsp]
snippets = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.soft-wrap]
wrap-at-text-width = true

[editor.smart-tab]
enable = false

[keys.insert]
C-space = "completion"
